[toolchain]
anchor_version = "0.30.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
coinpetitive = "5NLxDYs6Br5H8D3F3eq4JjGa8wX292onmvwKbLC3wEbU"

[programs.devnet]
coinpetitive = "5NLxDYs6Br5H8D3F3eq4JjGa8wX292onmvwKbLC3wEbU"

[provider]
cluster = "devnet"
wallet = "keypairs/keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
start-validator = "solana-test-validator --reset --bpf-program HXqZ2byZ8b1ALKr7MjZHiiMZN6oYGtByeSunm5J25K8K ./target/deploy/coinpetitive.so"
test-local = "anchor test --provider.cluster localnet"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/dumped_so_files/metadata.so"

[[test.genesis]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
program = "tests/dumped_so_files/TokenProgram.so"

[[test.genesis]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
program = "tests/dumped_so_files/AssociatedTokenAccountProgram.so"

[[test.genesis]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
program = "tests/dumped_so_files/Token2022Program.so"